"$schema": "https://json-schema.org/draft/2020-12/schema"
title: "Configuration file"
type: "object"
required: []
properties:
  server:
    type: "object"
    properties:
      host:
        type: "string"
      port:
        type: "number"
        minimum: 1024
        maximum: 65535
  database:
    type: "object"
    properties:
      driver:
        type: "string"
        oneof:
